### ISSUE TITLE
No changes to commit after running deploy script and modifying blog from dashboard

### ISSUE THREAD

**Issue by rolandtshen** [paladini/ghost-on-github-pages#12]
[INFO] Deploying to your Github repository...
sh: wget: command not found
On branch master
nothing to commit, working directory clean
Everything up-to-date

Even when I make changes to the dashboard by adding new blog posts or changing the title etc., git still doesn't detect any changes to commit.

**Comment by Lisheng2016** [comment]
=====>  sh: wget: command not found
wget is the tool used to get content from your local server.

shell is showing that you dont have wget installed. Install it and it should be working.
