### ISSUE TITLE
Mention node version

### ISSUE THREAD

**Issue by yiochen** [paladini/ghost-on-github-pages#3]
I ran into problem when installing Ghost due to unsupported node version. I am running 7.2.1. It turned out that Ghost [doesn't support that version currently](http://support.ghost.org/supported-node-versions/) . I would suggest adding the supported versions to README

**Comment by paladini** [comment]
Thank you for the suggestion, @yiochen ! :) 

Take a look in the updated `readme.md` file and let me know if you have any other enhancements to this repository.
